---
# tasks file for mysql
  - name: update os
    command: apt update

  - name: install mysql
    apt:
      name: "{{ var1 }}"
      state: present

  - name: start mysql
    service:
      name: mysql.service
      state: started

  - name: copy index.html
    copy:
      src: /home/ubuntu/index1.html
      dest: /home/ubuntu/index1.html
    notify: restart mysql
